;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	eval-last-sexp
	indent-for-tab-command
	isearch-abort
	jump-char-forward
	jump-char-process-char
	kill-region
	kill-sexp
	sp--self-insert-command
	sp-forward-slurp-sexp
	sp-splice-sexp-killing-around
	))

(setq mc/cmds-to-run-once
      '(
	))
